Classes/Domain/Model/Product.php, Configuration/TCA/tx_pxaproductmanager_domain_model_product.php, Tests/Unit/Domain/Model/ProductTest.php, ext_tables.sql
Should be added by external extension.
=> [TASK] remove import fields since no import functionality in extension

Classes/Controller/AbstractController.php, Classes/Controller/ProductController.php, Classes/Hook/PageLayoutView.php, Classes/UserFunction/ItemsProcessingFunction.php, Classes/Utility/MainUtility.php, Classes/ViewHelpers/LinkViewHelper.php, Configuration/FlexForms/flexform_pi1.xml, Configuration/TypoScript/constants.txt, Configuration/TypoScript/setup.txt, Resources/Private/Language/locallang_be.xlf, Tests/Unit/Utility/MainUtilityTest.php
1. Make it possible to exclude categories from url generation.
2. Allow user to choose products from categories selection in "Custom products mode"
=> New features

Configuration/TypoScript/Solr/setup.txt
Raise up products in search result by name and sku
=> [TASK] add special query fields for solr 

Classes/Domain/Model/Category.php, Classes/Domain/Model/Product.php, Configuration/RealUrl/realurl.php, Configuration/TCA/Overrides/sys_category.php, Configuration/TCA/Overrides/tx_pxaproductmanager_domain_model_product.php, Configuration/TCA/tx_pxaproductmanager_domain_model_product.php, Resources/Private/Language/locallang_csh_tx_pxaproductmanager_domain_model_product.xlf, Resources/Private/Language/locallang_db.xlf, Tests/Unit/Domain/Model/CategoryTest.php, Tests/Unit/Domain/Model/ProductTest.php, ext_tables.sql, ext_typoscript_setup.txt
Implement slug field for products and categories.
=> Slug field for TYPO3 9 routing 

Classes/LinkHandler/AbstractCKEditorLinkHandler.php, Resources/Private/Backend/Templates/LinkBrowser/ProductManager.html, Resources/Private/Language/locallang_be.xlf, Resources/Public/JavaScript/Backend/LinkHandler.js
Move improved link builder from new version to version that supports TYPO3 8
=> Typo3 8 improved link handler

Classes/Controller/AbstractController.php, Classes/Controller/AjaxProductsController.php, Classes/Controller/ProductController.php, Classes/Domain/Model/DTO/Demand.php, Classes/Domain/Model/DTO/FiltersAvailableOptions.php, Classes/Domain/Model/Filter.php, Classes/Domain/Repository/AttributeValueRepository.php, Classes/Domain/Repository/CategoryRepository.php, Classes/Domain/Repository/ProductRepository.php, Classes/Hook/PageLayoutView.php, Configuration/FlexForms/flexform_pi1.xml, Configuration/TCA/tx_pxaproductmanager_domain_model_filter.php, Configuration/TypoScript/setup.txt, Resources/Private/Language/locallang_be.xlf, Resources/Private/Language/locallang_csh_tx_pxaproductmanager_domain_model_filter.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Partials/Filtering/FilterType1.html, Resources/Private/Partials/Filtering/FilterType2.html, Resources/Private/Partials/Filtering/FilterType3.html, Resources/Private/Partials/Filtering/Filters.html, Resources/Private/Partials/JavaScript/FilteringJsSettings.html, Resources/Private/Partials/JavaScript/LazyLoadingJsConfiguration.html, Resources/Private/Templates/Product/LazyList.html, Resources/Public/JavaScript/ProductManager.Filtering.js, Resources/Public/JavaScript/ProductManager.LazyLoading.js, Tests/Functional/Controller/AbsctactControllerTest.php, Tests/Unit/Domain/Model/DTO/FiltersAvailableOptionsTest.php, Tests/Unit/Domain/Repository/ProductRepositoryTest.php, ext_tables.sql
New features:
1. Allow to change filter logic "AND" or "OR" between filters in flexform settings.
2. Allow to change filter logic per filter
=> Filters conjunction

Classes/ViewHelpers/Link/LinkViewHelper.php, Resources/Private/Templates/AjaxProducts/LatestVisited.html, Resources/Private/Templates/Product/ComparePreView.html, Resources/Private/Templates/Product/CompareView.html, Resources/Private/Templates/Product/GroupedList.html
=> [BUGFIX] Wrong name of link viewhelper

Classes/ViewHelpers/Link/LinkViewHelper.php, Configuration/FlexForms/flexform_pi1.xml, Resources/Private/Partials/Product/Card.html
=> Lazy list fixes

Classes/Utility/TCAUtility.php, Configuration/TCA/Overrides/sys_category.php, Resources/Private/Language/locallang_be.xlf, ext_conf_template.txt
1. Fix localization issue.
2. Make categories restriction to work same as others.
=> Categories TCA

Classes/Domain/Model/Order.php, Classes/Utility/OrderUtility.php, ext_tables.sql
With hook to add additional data to the hash.
=> WIP: [FEATURE] Persistable order state hash

Classes/Attributes/ValueMapper/AbstractMapper.php, Classes/Attributes/ValueMapper/FalMapper.php, Classes/Attributes/ValueMapper/GeneralMapper.php, Classes/Attributes/ValueMapper/MapperFactory.php, Classes/Attributes/ValueMapper/MapperInterface.php, Classes/Attributes/ValueMapper/MapperService.php, Classes/Attributes/ValueMapper/SelectBoxMapper.php, Classes/Domain/Model/Attribute.php, Classes/Domain/Model/AttributeSet.php, Classes/Domain/Model/AttributeValue.php, Classes/Domain/Model/Product.php, Resources/Private/Partials/Product/Attribute/Type1.html, Resources/Private/Partials/Product/Attribute/Type10.html, Resources/Private/Partials/Product/Attribute/Type2.html, Resources/Private/Partials/Product/Attribute/Type3.html, Resources/Private/Partials/Product/Attribute/Type4.html, Resources/Private/Partials/Product/Attribute/Type5.html, Resources/Private/Partials/Product/Attribute/Type6.html, Resources/Private/Partials/Product/Attribute/Type7.html, Resources/Private/Partials/Product/Attribute/Type8.html, Resources/Private/Partials/Product/Attribute/Type9.html, Resources/Private/Partials/Product/AttributeListing.html, Resources/Private/Partials/Product/AttributeSet/Default.html, Tests/Unit/Attributes/ValueMapper/FalMapperTest.php, Tests/Unit/Attributes/ValueMapper/GeneralMapperTest.php, Tests/Unit/Attributes/ValueMapper/MapperServiceServiceTest.php, Tests/Unit/Attributes/ValueMapper/SelectBoxMapperTest.php, Tests/Unit/Domain/Model/AttributeTest.php, Tests/Unit/Domain/Model/AttributeValueTest.php, Tests/Unit/Domain/Model/ProductTest.php
mapping attribute values to attributes will use incorrect values in frontend
=> [!!!][TASK] use attributeValues on products to fetch attribute values in templates

Configuration/TCA/tx_pxaproductmanager_domain_model_attributevalue.php
… product manager tables are created
=> [BUGFIX] Fix exeption when table isnt created

Classes/Backend/FormDataProvider/NewAttributeRelationRecordsDataProvider.php, Classes/Service/Url/UrlBuilderService.php
Removed unnecessary parameters, because impossible to beautify url with routeEnhancer
=> [BUGFIX] removed unnecessary parameters for url builder

Classes/Domain/Model/Product.php, Classes/Domain/Repository/AbstractDemandRepository.php, Classes/Domain/Repository/ProductRepository.php, Classes/Domain/Resource/Product.php, Configuration/TypoScript/setup.typoscript
also remove typed property to allow debug of product model in fluid
=> [FEATURE] option to add additional fields to be included in product lists

Classes/Command/FixDuplicateAttributeValuesCommand.php, Classes/Command/RemoveOrphanAttributeValuesCommand.php, Configuration/Services.yaml, Configuration/TCA/tx_pxaproductmanager_domain_model_attributevalue.php
also add two new commands to temporary fix invalid attributevalues and rii records
* add new command to fix dupliacate attribute values
* add a remove orphan records command
=> [BUGFIX] allow non-admin users to access attribute values on the root-level

Classes/Hook/Solr/DetectSerializedValue.php, Classes/UserFunction/Solr/AbstractValue.php, Classes/UserFunction/Solr/AttributeMultiValue.php, Classes/UserFunction/Solr/AttributeValue.php, Configuration/Services.yaml, Configuration/TypoScript/Solr/setup.typoscript, ext_emconf.php
Also support "multi" value fields, e.g. multi select.
=> [FEATURE] update solr userFunc so it can index "option" values, not only plain strings.

Classes/Seo/XmlSitemap/ProductsXmlSitemapDataProvider.php, Configuration/TypoScript/Sitemap/setup.typoscript
Also modify it and base it on RecordsXmlSitemapDataProvider instead of using demand from product listings.
=> [TASK] fix sitemap

Classes/Controller/AbstractController.php, Configuration/TCA/tx_pxaproductmanager_domain_model_attributevalue.php, Configuration/TypoScript/setup.typoscript
[BUGFIX] fix performance on edit products with large amount of attribute values
[FEATURE] add option to set product list view menu start page id instead of using current page
=> [TASK] fix performance issue and add option to set page id for product list menu

Configuration/TCA/tx_pxaproductmanager_domain_model_attribute.php, Configuration/TCA/tx_pxaproductmanager_domain_model_attributeset.php, Configuration/TCA/tx_pxaproductmanager_domain_model_attributevalue.php, Configuration/TCA/tx_pxaproductmanager_domain_model_filter.php, Configuration/TCA/tx_pxaproductmanager_domain_model_link.php, Configuration/TCA/tx_pxaproductmanager_domain_model_option.php, Configuration/TCA/tx_pxaproductmanager_domain_model_order.php, Configuration/TCA/tx_pxaproductmanager_domain_model_orderconfiguration.php, Configuration/TCA/tx_pxaproductmanager_domain_model_orderformfield.php, Configuration/TCA/tx_pxaproductmanager_domain_model_product.php
Update l10n_parent foreign_table_where and only load parent record.
=> [BUGFIX] fix performance issues on edit and save

Configuration/TCA/tx_pxaproductmanager_domain_model_option.php
=> [BUGFIX] added proper TCA configuration

Classes/Controller/AbstractController.php, Configuration/TypoScript/setup.typoscript
=> [FEATURE] added possibility to exclude pages from menu

Classes/Controller/AbstractController.php, Classes/Event/Controller/ExcludePagesFromMenuEvent.php
=> [FEATURE] added excludePagesFromMenu event

.github/workflows/ci.yml
=> [TASK] update github actions

Classes/Hook/ProcessDatamap/AttributeSaveProcessDatamap.php, ext_tables.php
When a new option is added to a attribute, it will not be available in the products until the main system cache is cleared.
This addition will try to detect if system cache needs to be cleared when an atttrbute is saved. 
=> [TASK] check if system cache needs to be cleared on attribute save

Classes/Hook/ItemsProcFunc/GeneralItemsProcFunc.php, Configuration/TCA/tx_pxaproductmanager_domain_model_attribute.php, Configuration/TCA/tx_pxaproductmanager_domain_model_filter.php, Configuration/TCA/tx_pxaproductmanager_domain_model_link.php, Configuration/TCA/tx_pxaproductmanager_domain_model_option.php, Configuration/TCA/tx_pxaproductmanager_domain_model_product.php, Configuration/TCA/tx_pxaproductmanager_domain_model_producttype.php
After l10nmanager extension was installed, an exception was thrown when a editor saved a product.
=> [BUGFIX] removes t3ver_label references, updates l10n_parent TCA config

Classes/Backend/Tree/BrowserTreeView.php, Configuration/TCA/tx_pxaproductmanager_domain_model_product.php, ext_localconf.php
=> [BUGFIX] display crdate and tstamp of products as DateTime in BE lists

Classes/Domain/Model/Attribute.php, Configuration/TCA/tx_pxaproductmanager_domain_model_attribute.php, Documentation/Editors/ProductAttributes/Index.rst, Resources/Private/Language/locallang_db.xlf, ext_tables.sql
Removes the property showInCompare from the Attribute model. The property will be supplied by the pxa_pm_compare extension in the future.
=> [!!!][TASK] Remove showInCompare property

Configuration/TCA/tx_pxaproductmanager_domain_model_attributeset.php
Needs to update the database, new fields are added to table tx_pxaproductmanager_domain_model_attributeset.
=> [!!!][TASK] make attributesets localizable

ext_tables.sql
=> [TASK] add some indexes

Classes/Backend/FormDataProvider/NewAttributeRelationRecordsDataProvider.php, Classes/Hook/ProcessDatamap/ProductInheritanceProcessDatamap.php, Classes/Utility/AttributeUtility.php, Classes/Utility/RelationInheritanceIndexUtility.php, Configuration/TCA/tx_pxaproductmanager_domain_model_attribute.php, Configuration/TCA/tx_pxaproductmanager_domain_model_attributeset.php, Configuration/TCA/tx_pxaproductmanager_domain_model_producttype.php, Resources/Private/Language/locallang_be.xlf
added allowLanguageSynchronization to some fields to make localization handling easier
attribute values shoud inherit language from product in "dynamic" attributes
=> [BUGFIX] remove old inherited data when parent product is changed on product

Classes/Hook/ProcessDatamap/ProductInheritanceProcessDatamap.php
=> [BUGFIX] cast to integer data type added

Classes/Domain/Repository/ProductRepository.php
=> [BUGFIX] fix group by error

Configuration/TypoScript/Solr/setup.typoscript
=> [BUGFIX] prevent error when indexing products in solr

Configuration/FlexForms/flexform_product_render.xml
Changed values to dynamic values of current record, so from now it's fetching correct filter records according to language
=> [BUGFIX] hardcoded values changed to dynamic

Classes/Attributes/ValueMapper/FalMapper.php, Classes/Attributes/ValueMapper/SelectBoxMapper.php, Classes/Domain/Resource/Product.php, Classes/Utility/AttributeUtility.php
Changed fetching functionallity of additional attributes, due to performance issue Extbase entities was removed and now simple types are using instead
=> [TASK] changed fetching of additional attributes attributesValues

Classes/Domain/Resource/Product.php, Classes/Utility/AttributeUtility.php, Classes/ViewHelpers/GetAttributeValuesForProductViewHelper.php
=> [TASK] added getAttributeValuesForProduct viewhelper

Classes/ViewHelpers/RenderMultipleViewHelper.php
=> [BUGFIX] allow empty rendering stacks

Classes/ViewHelpers/RenderMultipleViewHelper.php
=> [BUGFIX] prevent empty extbase configuration when other extensions are rendered from same template.

Classes/Domain/Collection/Collection.php, Classes/Domain/Model/Product.php, Classes/Domain/Resource/Product.php, Configuration/TCA/Overrides/sys_file_reference.php, Tests/Unit/Domain/Model/ProductTest.php
=> [TASK] added image types

Configuration/TCA/Overrides/sys_file_reference.php
=> [BUGFIX] added excludded attribute to TCA

Configuration/TCA/tx_pxaproductmanager_domain_model_product.php, ext_tables.sql
=> [TASK] allowLanguageSynchronization on product images

Classes/UserFunction/Solr/AbstractValue.php, Configuration/TypoScript/PageTS/mod.SHARED.ts
=> [BUGFIX] use localized product to fetch attribute value for if set

ext_localconf.php
=> [TASK] add product display doktype to yoast_seo:s allowedDoktypes if loaded

Classes/UserFunction/Solr/AbstractValue.php
=> [BUGFIX] fetch correct uid without cast to prevent uid to be 0

Configuration/TCA/Overrides/pages.php
Fix page type icon to prevent a faulty icon being displayed in the backend.
=> [BUGFIX] Fix page type icon

composer.json
=> [TASK] Update to Composer v2

Classes/Domain/Model/Product.php
Cache ObjectStorage properties in Product domain model.
=> [TASK] Cache ObjectStorage properties in Product domain model

Resources/Public/Css/ProductManager.swiper.css
Add cursor pointer to thumbnails in product single view for swiper.
=> [BUGFIX] Add cursor pointer to thumbnails in product single view for swiper

.github/workflows/ter-release.yml
Add TER release Github Action workflow.
=> [TASK] Add TER release Github Action workflow

.github/workflows/ci.yml, .github/workflows/ter-release.yml
Add TER release Github Actions workflow.
=> [TASK] Add TER release Github Actions workflow

.github/workflows/ci.yml, README.md
Fixes: #203 
Update README documentation.
=> [TASK] Update README documentation

README.md, docker-compose.yml
=> [DOC] Adjusted README.md, added docker-compose.yml for building local documentation

Documentation/Developers/PhpApi/Index.rst
This fixes the links on the images. Previously the links to the isolated images wouldn't work because the path to the images when documentation is generated are different.
=> [BUGFIX] Documentation, image target generated broken links

Documentation/Integrators/Configuration/Index.rst
This fixes the images in the documentation on the Integrators/Configuration-page.
=> [BUGFIX] Documentation, image reference case sensitivity

Configuration/TypoScript/Swiper/setup.typoscript, Configuration/TypoScript/constants.typoscript, Configuration/TypoScript/setup.typoscript, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Product/Attribute/Type2.html, Resources/Private/Partials/Product/AttributeListing.html, Resources/Private/Partials/Product/AttributeSet/Default.html, Resources/Private/Partials/Product/FileLinks.html, Resources/Private/Partials/Product/Links.html, Resources/Private/Partials/Product/ListImage.html, Resources/Private/Partials/Product/Related.html, Resources/Private/Partials/Product/SwiperRelated.html, Resources/Private/Templates/LazyProduct/List.html, Resources/Private/Templates/Page/ProductDisplaySample.html, Resources/Private/Templates/ProductRender/List.html, Resources/Private/Templates/ProductRender/Show.html, Resources/Private/Templates/Stacks/Product/Collapsible.html, Resources/Private/Templates/Stacks/Product/Gallery.html, Resources/Private/Templates/Stacks/Product/GalleryItem.html, Resources/Private/Templates/Stacks/Product/Images.html, Resources/Private/Templates/Stacks/Product/LinksList.html, Resources/Private/Templates/Stacks/Product/LinksListItems.html, Resources/Private/Templates/Stacks/Product/Sku.html, Resources/Private/Templates/Stacks/Product/SwiperImages.html, Resources/Public/Css/ProductManager.swiper.css, Resources/Public/Css/product_manager_basic.css, Resources/Public/Icons/Svg/chevron-up.svg, Resources/Public/JavaScript/ProductManager.swiper.js, Resources/Public/JavaScript/collapse.js
=> [TASK] changes to single-view template, slider, render stacks, js, css

Documentation/Introduction/Index.rst
Update to correct Paypal link in Documentation.
=> [BUGFIX] Update to correct Paypal link in Documentation

README.md
Fixes: #348
Add overview in README.
=> [TASK] Add overview in README

Documentation/Developers/ModelExtender/ControllerExtending/Index.rst, Documentation/Developers/ModelExtender/Index.rst, Documentation/Developers/PhpApi/Index.rst, Documentation/Editors/ProductAttributeSets/Index.rst, Documentation/Editors/ProductAttributes/Index.rst, Documentation/Includes.txt, Documentation/Installation/Index.rst, Documentation/Integrators/Configuration/Index.rst, Documentation/Integrators/Customizations/AttributeSets/CustomLayout.rst, Documentation/LegacyInstallation/Index.rst, Documentation/Products/Index.rst, Documentation/Settings.cfg
Fix minor reST bugs in documentation.
=> [DOCS] Fix documentation

composer.json, ext_emconf.php
Update and use the released version of ''demander''.
=> [!!!][TASK] Update and use the released version of ''demander''

Documentation/Integrators/Configuration/Index.rst
=> [TASK] Documentation, breadcrumb

composer.json
Add doctrine/dbal as a hard requirement.
=> [!!!][TASK] Add doctrine/dbal as a hard requirement

.github/workflows/ci.yml, Classes/ViewHelpers/SvgViewHelper.php, Resources/Private/Partials/Product/FileLinks.html
=> [TASK] update Svgviewhelper

Classes/Domain/Model/Product.php
Suppress error on missing main image.
=> [BUGFIX] Suppress error on missing main image

Resources/Private/Partials/Product/AttributeListing.html, Resources/Private/Templates/Stacks/Product/AttributeListing.html
=> [TASK] change attribute listing if statement

Resources/Private/Templates/Stacks/Product/GalleryItem.html, Resources/Private/Templates/Stacks/Product/SwiperImages.html, Resources/Public/Css/ProductManager.swiper.css, Resources/Public/Css/product_manager_basic.css
=> [TASK] video element in single view

Classes/Domain/Model/Product.php
=> [BUGFIX] fetch child products based on default parent product id

Classes/Hook/ItemsProcFunc/ProductItemsProcFunc.php, composer.json
Prevent PHP error for empty relationHandler in ProductItemsProcFunc.
=> [BUGFIX] Prevent PHP error for empty relationHandler in ProductItemsProcFunc

Configuration/TypoScript/Api/page_lazy_loading.typoscript
Add caching for Product List when Googlebot is crawling.
=> [TASK] Add caching for Product List when Googlebot is crawling

Classes/Controller/ProductRenderController.php, Classes/Domain/Resource/Product.php, Configuration/TypoScript/constants.typoscript, Configuration/TypoScript/setup.typoscript, Documentation/Configuration/Index.rst
=> [BUGFIX] use overlayed attributevalue in product list

Classes/Domain/Repository/ProductRepository.php
Fixes query builder for category filtering. Currently the invalid column "tpppm.uid_local" is used in "group by" where "scrm.uid_foreign" should be used.
=> Fix category filter query builder

Classes/Backend/FormEngine/FieldWizard/HiddenAttributeTypeValueFieldWizard.php
=> Add passthrough for sys_language uid in HiddenAttributeTypeValueFieldWizard

Resources/Private/Partials/Product/Attribute/Type1.html
Check for that the attribute.identifier and not renderValue. This is to prevent that values of for example type ''000'' do not get rendered at all.
=> [BUGFIX] Check for that the attribute.identifier and not renderValue

Classes/Domain/Repository/ProductRepository.php
Fixes: #404
Remove unnecessary groupBy for getProductPagesSubQuery.
=> [BUGFIX] Remove unnecessary groupBy for getProductPagesSubQuery

Configuration/TypoScript/Api/page_lazy_loading.typoscript
Remove GoogleBot check for lazy loading.
=> [BUGFIX] Remove GoogleBot check for lazy loading
